version: "3.5"
services:
  limiter:
    image: ghcr.io/systematiccaos/limiter/limiter:latest
    environment:
      - MQTT_CLIENT_ID="${MQTT_CLIENT_ID}"
      - MQTT_URL="${MQTT_URL}"
      - MQTT_USER="${MQTT_USER}" 
      - MQTT_PASSWORD="${MQTT_PASSWORD}"
      - MQTT_TOPIC_SOLAR_POWER="${MQTT_TOPIC_SOLAR_POWER}"
      - MQTT_TOPIC_TOTAL_POWER="${MQTT_TOPIC_TOTAL_POWER}"
      - MQTT_PUB_TOPIC="${MQTT_PUB_TOPIC}"